/* SPDX-License-Identifier: GPL-2.0 */

SOFTIRQ_VECTOR(HI)
SOFTIRQ_VECTOR(TIMER)
SOFTIRQ_VECTOR(NET_TX)
SOFTIRQ_VECTOR(NET_RX)
SOFTIRQ_VECTOR(BLOCK)
SOFTIRQ_VECTOR(IRQ_POLL)
SOFTIRQ_VECTOR(TASKLET)
SOFTIRQ_VECTOR(SCHED)
SOFTIRQ_VECTOR(HRTIMER)
SOFTIRQ_VECTOR(RCU)    /* Preferable RCU should always be the last softirq */
